stages:
  data_ingestion:
    cmd: python main_pipeline.py --step ingestion
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw/

  data_preparation:
    cmd: python main_pipeline.py --step preparation
    deps:
    - src/data_preparation.py
    - data/raw/
    outs:
    - data/cleaned/

  data_transformation:
    cmd: python main_pipeline.py --step transformation
    deps:
    - src/data_transformation_storage.py
    - data/cleaned/
    outs:
    - data/processed/

  feature_store:
    cmd: python main_pipeline.py --step feature_store
    deps:
    - src/feature_store.py
    - data/processed/
    outs:
    - data/feature_store/